# Generated by Django 2.1 on 2019-04-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190414_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='photo/Album/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='music',
            field=models.FileField(null=True, upload_to='music/Track/%Y/%m/%d/'),
        ),
    ]
